name: Tinker CI

on:
  workflow_dispatch:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup GO env
        run: go env -w CGO_ENABLED=0

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Before build
        run: |
          ./hack/verify-gofmt.sh
          ./hack/verify-govet.sh
          ./hack/verify-golint.sh
          go mod verify
